# main playbook: site.yml
---

# - import_playbook: play-centos.yml

# - import_playbook: play-debian.yml

# - import_playbook: play-fedora.yml

# - import_playbook: play-ubuntu.yml

# - import_playbook: play-macos.yml

- import_playbook: play-virtualbox.yml