---
# defaults file for common

time_host: 0.north-america.pool.ntp.org
time_service: ntpd
timezone: America/Los_Angeles

common_packages:
  - git
  - lsof
  - make
  - moreutils
  - net-tools
  - vim
  - wget
  - chrony
  - ntp
