---
# defaults file for common

common_packages:
  - git
  - lsof
  - make
  - moreutils
  - net-tools
  - ntp
  - vim

ntp_host: 0.north-america.pool.ntp.org
ntp_service: ntpd

timezone: America/Los_Angeles
