# install vagrant on RedHat systems
---

- name: check if vagrant already installed
  stat:
    path: ./vagrant_{{ vagrant_version }}_x86_64.rpm
  register: vagrant_rpm_exists
# - debug: var=vagrant_rpm_exists

# this will work if using a proxy server while
# rpm directly with yum will not (https not supported)
- name: downloading vagrant rpm (this may take a couple minutes)
  shell: "wget {{ vagrant_url }}{{ vagrant_version }}/vagrant_{{ vagrant_version }}_x86_64.rpm"
  args:
    warn: false # set warn=false to prevent warning
    creates: vagrant_{{ vagrant_version }}_x86_64.rpm
  register: vagrant_wget_result
# - debug: var=vagrant_wget_result.stderr_lines

# installs into /opt/vagrant and /usr/bin/vagrant
- name: installing vagrant rpm file (this amy take a minute)
  yum:
    name: "./vagrant_{{ vagrant_version }}_x86_64.rpm"
    state: present
    # allow_unauthenticated: True
  when: not vagrant_wget_result.failed
  register: vagrant_yum_rpm
# - debug: var=vagrant_yum_rpm.results
