galaxy_info:
  author: "Michael Vilain"
  description: install vagrant

  license: license (GPLv2, CC-BY, etc)

  min_ansible_version: 1.2

  platforms:
  - name: EL
    versions:
    - 6
    - 7
  - name: Fedora
    versions:
      - 21
      - 22
      - 23
      - 24
      - 25
      - 26
      - 27
      - 28
  - name: Ubuntu
    versions:
    - precise (12.04)
    - trusty (14.04)
    - xenial (16.04)
    - bionic (18.04)
  - name: Debian
    versions:
    - 8.0 (jessie)
    - 9.0 (stretch)
    - 10.0 (buster)

  galaxy_tags:
    - networking

dependencies: []
