# install virtualbox on MacOS/Darwin systems
# the easiest way to do this is to ensure brew is installed and use that
# you won't get the lastest version of virtualbox, but it's less work
---

- debug: msg="Not implemented yet!"

# - name: check if virtualbox already installed
#   stat:
#     path: ./virtualbox_{{ virtualbox_version }}_x86_64.dmg
#   register: virtualbox_rpm_exists
# # - debug: var=virtualbox_rpm_exists

# - name: downloading virtualbox rpm (this may take a couple minutes)
#   shell: "wget {{ virtualbox_url }}{{ virtualbox_version }}/virtualbox_{{ virtualbox_version }}_x86_64.dmg"
#   args:
#     warn: false # set warn=false to prevent warning
#     creates: virtualbox_{{ virtualbox_version }}_x86_64.dmg
#   register: virtualbox_wget_result
# # - debug: var=virtualbox_wget_result.stderr_lines

# # installs into /usr/local/bin/virtualbox
# - name: installing virtualbox from dmg
#   yum:
#     name: "./virtualbox_{{ virtualbox_version }}_x86_64.dmg"
#     state: present
#     # allow_unauthenticated: True
#   when: not virtualbox_wget_result.failed
#   register: virtualbox_yum_rpm
# - debug: var=virtualbox_yum_rpm.results
