# install for Debian virtualbox
---

### this won't work if you're behind a proxy server
- name: adding virtualbox key
  apt_key:
    url: "{{ deb_vb_keyurl }}/{{ deb_vb_key }}"
    state: present
  when: ( ansible_distribution == "Ubuntu" and ansible_distribution_version == "18.04" ) or 
        ( ansible_distribution == "Debian" and ansible_distribution_version|int == 9 )

# this may not work if using a proxy server
- name: adding virtualbox repo
  lineinfile:
    path: /etc/apt/sources.list
    backup: yes
    line: deb http://download.virtualbox.org/virtualbox/debian {{ ansible_distribution_release }} contrib

- name: installing virtualbox (this may take few mintues)
  apt:
    name: virtualbox-5.2
    state: present
    update_cache: yes
  register: vb_install
- debug: var=vb_install
