# install for Debian virtualbox
---

# vagrant doesn't support https behind proxy
# none of this won't work behind a proxy server
- name: adding virtualbox key
  apt_key:
    url: "{{ deb_vb_keyurl }}/{{ deb_vb_key }}"
    state: present
  when: ( ansible_distribution == "Ubuntu" and ansible_distribution_major_version|int == 18 ) or 
        ( ansible_distribution == "Debian" and ansible_distribution_version|int == 9 )

- name: adding older virtualbox key
  apt_key:
    url: "{{ deb_vb_keyurl }}/{{ deb_vb_old_key }}"
    state: present
  when: ( ansible_distribution == "Ubuntu" and ansible_distribution_major_version|int == 16 ) or 
        ( ansible_distribution == "Ubuntu" and ansible_distribution_major_version|int == 14 ) or
        ( ansible_distribution == "Debian" and ansible_distribution_version|int == 8 )

- name: adding virtualbox repo
  lineinfile:
    path: /etc/apt/sources.list
    backup: yes
    line: deb http://download.virtualbox.org/virtualbox/debian {{ ansible_distribution_release }} contrib

- name: installing virtualbox (this may take a few mintues)
  apt:
    name: virtualbox-5.2
    state: present
    allow_unauthenticated: yes
    update_cache: yes
  when: ( ansible_distribution == "Ubuntu" and ansible_distribution_major_version|int != 12 )
  register: vb_install
# - debug: var=vb_install

- name: installing old virtualbox (this may take a few mintues)
  apt:
    name: virtualbox-5.1
    state: present
    allow_unauthenticated: yes
    update_cache: yes
  when: ( ansible_distribution == "Ubuntu" and ansible_distribution_major_version|int == 12 )
  register: vb_install
# - debug: var=vb_install