# install for Debian ansible
---

- name: enable backports repository
  apt_repository:
    repo: "deb http://ftp.debian.org/debian {{ ansible_distribution_release }}-backports main"
    state: present
    filename: "{{ ansible_distribution_release }}_backports"
  when: ansible_distribution_release

- name: install ansible
  apt:
    name: ansible
    update_cache: yes 
    state: present
    default_release: "{{ ansible_distribution_release }}-backports"
