---
# CentOS install tasks for common
# if there are more tasks that split on version, 
# put them in their own tasks file. For now two is OK

- name: CentOS packages
  package: name={{ item }} state=present
  with_items:
    - "{{ CentOS_packages }}"
