# Debian tasks for common
---
- name: Debian packages
  package: name={{ item }} state=installed
  with_items:
    - "{{ Debian_packages}}"

- name: configure Debian NTP and timezone
  service: 
    name: "{{ Debian_ntp_service }}" 
    state: started
    enabled: yes
