# Fedora install tasks for common
---
# this requires specific package manager because vim requires vim-common

# https://bugzilla.redhat.com/show_bug.cgi?id=1329015
# dnf is installed since F18...fixed in f27+
- name: Fedora vim fixes vim-minimal which is too old
  command: dnf update -y --allowerasing vim-minimal
  args:
    warn: no
  register: vim_min
  when: 
  - ansible_distribution_major_version|int > 21
  - ansible_distribution_major_version|int <= 26

- name: Fedora 21 yum packages
  yum: 
    name: "{{ item }}"
    state: present
    skip_broken: yes
    update_cache: yes
  register: package
  with_items:
    - "{{ Fedora_packages }}"
  when: ansible_distribution_major_version|int == 21

- name: Fedora 22+ dnf packages
  dnf: 
    name: "{{ item }}"
    state: latest
  register: dnf
  with_items:
    - "{{ Fedora_packages }}"
    - vim-common   # older version collides with vim-common until F27
  when: ansible_distribution_major_version|int > 21

#- debug: var="{{ item }}"
#  with_items:
#  - package
#  - vim_min.stdout_lines
#  - dnf.results
