# Fedora install tasks for common
---
- name: Fedora packages
  package: name={{ item }} state=present
  with_items:
    - "{{ Fedora_packages }}"

# Most distros use ntp but CentOS 8 and Ubuntu 20 use chrony
#- include_tasks: ntp.yaml
