# Fedora install tasks for common
---
# this requires specific package manager because vim requires vim-common

# https://bugzilla.redhat.com/show_bug.cgi?id=1329015
# (dnf is installed since F18...fixed in f27+)
- name: fix Fedora[22-26] vim-minimal
  command: dnf update -y --allowerasing vim-minimal
  args:
    warn: no
  register: vim_min
  when: 
  - ansible_distribution_major_version|int > 21
  - ansible_distribution_major_version|int <= 26

- name: fix Fedora[22-23] python2 dnf not allowing signatures
  command: dnf install -y python-yumdaemon python-pip
  args:
    warn: no
  register: yumdaemon
  when: 
  - ansible_distribution_major_version|int > 21
  - ansible_distribution_major_version|int <= 23

- name: Fedora 22-23 pip package
  pip: 
    name: yum
    state: present
  register: yum
  when: 
  - ansible_distribution_major_version|int > 21
  - ansible_distribution_major_version|int <= 23

# ansible 2.7 deprecates with_items and nosquash, use variable directly
- name: Fedora packages
  package:
    name: '{{ item }}'
    state: present
  register: package
  with_items:
    - '{{ Fedora_packages }}'
  when: 
  - ansible_distribution_major_version|int >= 21
  - ansible_distribution_major_version|int <= 23

# ansible 2.7 deprecates with_items and nosquash, use variable directly
#- name: Fedora 21-23 bypass broken dnf module (not idempotent)
#  command: dnf install -y '{{ item }}'
#  args:
#    warn: no
#  register: package
#  with_items:
#    - '{{ Fedora_packages }}'
#  when: 
#  - ansible_distribution_major_version|int >= 21
#  - ansible_distribution_major_version|int <= 23

- name: Fedora 24+ dnf packages
  dnf: 
    name: "{{ Fedora_packages }}"
    state: latest
  register: dnf
  when: ansible_distribution_major_version|int > 23

# Fedora uses ntpd
- name: Fedora set
  set_fact: 
    time_service: ntpd
