# Fedora install tasks for common
---
# this requires specific package manager because vim requires vim-common

# https://bugzilla.redhat.com/show_bug.cgi?id=1329015
# (dnf is installed since F18...fixed in f27+)
- name: fix Fedora vim-minimal which is too old
  command: dnf update -y --allowerasing vim-minimal
  args:
    warn: no
  register: vim_min
  when: 
  - ansible_distribution_major_version|int > 21
  - ansible_distribution_major_version|int <= 26

# ansible 2.7 deprecates with_items and nosquash, use variable directly
- name: Fedora 21 yum packages
  yum: 
    name: '{{ Fedora_packages }}'
    state: present
    skip_broken: yes
    update_cache: yes
  register: package
  when: ansible_distribution_major_version|int == 21

# ansible 2.7 deprecates with_items and nosquash, use variable directly
- name: Fedora 22+ dnf packages (this may take a few minutes on Fedora 32)
  dnf: 
    name: "{{ Fedora_packages }}"
    state: latest
  register: dnf
  when: ansible_distribution_major_version|int > 21

#- debug: var="{{ item }}"
#  with_items:
#  - package
#  - vim_min.stdout_lines
#  - dnf.results
