---
# tasks file for common

#OS_FAMILY = dict(
#  RedHat = 'RedHat', Fedora = 'RedHat', CentOS = 'RedHat', Scientific = 'RedHat',
#  SLC = 'RedHat', Ascendos = 'RedHat', CloudLinux = 'RedHat', PSBM = 'RedHat',
#  OracleLinux = 'RedHat', OVS = 'RedHat', OEL = 'RedHat', Amazon = 'RedHat',
#  XenServer = 'RedHat', Ubuntu = 'Debian', Debian = 'Debian', SLES = 'Suse',
#  SLED = 'Suse', OpenSuSE = 'Suse', SuSE = 'Suse', Gentoo = 'Gentoo',
#  Archlinux = 'Archlinux', Mandriva = 'Mandrake', Mandrake = 'Mandrake',
#  Solaris = 'Solaris', Nexenta = 'Solaris', OmniOS = 'Solaris', OpenIndiana = 'Solaris',
#  SmartOS = 'Solaris', AIX = 'AIX', Alpine = 'Alpine', MacOSX = 'Darwin',
#  FreeBSD = 'FreeBSD', HPUX = 'HP-UX'
#)

# - block:
#   - debug: var=ansible_os_family
#   - debug: var=ansible_distribution
#   - debug: var=ansible_distribution_major_version
#   - debug: var=ansible_distribution_release
#   - debug: var=ansible_distribution_version

- name: set specific variables for distributions
  block:
    - include_vars: "{{ item }}"
      with_first_found:
        - files:
          - "{{ ansible_os_family }}.yml"
    - include_vars: "{{ item }}"
      with_first_found:
        - files:
          - "{{ ansible_distribution }}.yml"
    - debug: var=group_vars


- name: Install common packages (this may take a while)
  package: name={{ item }} state=present
  with_items:
    - "{{ common_packages }}"

# note: the following included tasks might configure and enable stuff in common_packages
# requires Debian.yml, RedHat.yml, CentOS.yml, Fedora.yml, and Ubuntu.yml

- include_tasks: "{{ ansible_os_family }}.yml"
- include_tasks: "{{ ansible_distribution }}.yml"


- name: set timezone and check ntp
  block:
    - timezone: name={{ timezone }}
    - shell: sleep 4; date
      register: tod 
    - command: ntpq -c peer
      register: ntpq
    - debug: var=tod.stdout_lines
    - debug: var=ntpq.stdout_lines
