# Ubuntu install tasks for common
---
- name: Ubuntu packages
  package: name={{ item }} state=present
  with_items:
    - "{{ Ubuntu_packages }}"
  when: ansible_distribution != "Ubuntu" and ansible_distribution_major_version != "18"

# specific packages for Ubuntu18
- name: Ubuntu18 packages
  package: name=iproute2 state=present
  when: ansible_distribution == "Ubuntu" and ansible_distribution_major_version == "18"
